version: '3.1'
services:
  ecc-postgresql:
    container_name: postgresql-aqc
    image: postgres:11.5
    environment:
      - POSTGRES_USER=postgres_rw_user
      - POSTGRES_PASSWORD=postgres_rw_password
      - POSTGRES_DB=app_questionario_compliance_db
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432